### ISSUE TITLE
需求：支持buildroot支持的package查询

### ISSUE THREAD

**Issue by gupeng1978** [gupeng1978/qemu_builds#1]
完成get_buildroot_packages函数，并给出demo例子。
实现机制：读取buidroot的package目录下所有mk文件，搜索XXX_VERSION找到pacakge名称以及路径信息。
比如用户输入opencv, 那么会搜索到OPENCV3_VERSION = 3.4.19，OPENCV4_VERSION = 4.6.0，那么返回
{'opencv3',  '3.4.19'}, {'opencv4'， ‘4.6.0’}，注意package名称转为小写。
@mkx171217

**Comment by mkx171217** [comment]
已实现，demo见sample/qemu_linux_packages_version.py。

不能处理以下情况：
1. xxx.mk中未定义XXX_VERSION，例如zlib、pkg-kconfig
2. xxx.mk中虽然定义了XXX_VERSION，但却是间接定义的。例如cmake.mk中定义内容如下：
```
CMAKE_VERSION_MAJOR = 3.22
CMAKE_VERSION = $(CMAKE_VERSION_MAJOR).3
```
其他的还有：libgtk2、libgtk3、libssh、libsigc2、libsigc、qt5、qt6
