### ISSUE TITLE
需求：支持build的profile信息

### ISSUE THREAD

**Issue by gupeng1978** [gupeng1978/qemu_builds#2]
完成Build类的下面接口，使用buildroot的graph-build以及graph-depends，返回输出目录或文件名称。
```
def graph_build(self):
        pass
    
def graph_depends(self):
      pass
```

@mkx171217

**Comment by mkx171217** [comment]
已实现。
graph_build返回的是一个目录的路径，例如/home/xxxx/qemu_builds/output/qemu_aarch64/graphs/，这个目录下会有多个pdf文件，如：build.hist-build.pdf、build.pie-steps.pdf、build.hist-name.pdf、build.timeline.pdf、build.pie-packages.pdf、build.hist-duration.pdf。
graph_depends返回的是一个文件的路径，例如/home/xxxx/qemu_builds/output/qemu_aarch64/graphs/graph-depends.pdf。

使用此功能需安装python3的matplotlib
